DFShop/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DFShop.Models;
using System.Web.Mvc;

namespace DFShop.Controllers
{
    public class CartController : Controller
    {
        /// global DB instance
        DontFretEntities db = new DontFretEntities();

        /// <summary>
        /// GET: Cart
        /// </summary>
        /// <returns>cart view</returns>
        public ActionResult Index()
        {
            var shoppingCart = Cart.GetCart(this.HttpContext);

            var model = new CartViewModel
            {
                CartEntries = shoppingCart.GetCartEntries(),
                ShoppingCartTotal = shoppingCart.GetCartTotal()
            };

            return View(model);
        }

        /// <summary>
        /// Adds the current product to the cart
        /// </summary>
        /// <param name="productID"></param>
        /// <returns>Cart view with product added</returns>
        public ActionResult AddToCart(int productID)
        {
            var newEntry = db.Products.Single(p => p.ProductID == productID);
            newEntry.StockLevel--;

            var cart = Cart.GetCart(this.HttpContext);

            cart.AddToCart(newEntry);

            return RedirectToAction("Index");

        }

        /// <summary>
        /// POST: Remove cart entry
        /// </summary>
        /// <param name="entryID"></param>
        /// <returns></returns>
        public ActionResult RemoveEntry(int id)
        {
            var cart = Cart.GetCart(this.HttpContext);

            string productName = db.ShoppingCarts.Single(s => s.EntryID == id).Product.ProductName;

            int entryCount = cart.RemoveEntry(id);

            var results = new RemoveCartViewModel
            {
                Message = Server.HtmlEncode(productName) +
                              " has been removed from your shopping cart.",
                ShoppingCartTotal = cart.GetCartTotal(),
                ShoppingCartCount = cart.GetCartCount(),
                ItemCount = entryCount,
                DeleteId = id
            };
            return Json(results);

        }

        /// <summary>
        /// Shows the user how many times are currently in their cart in the navbar
        /// </summary>
        /// <returns>partial cart view</returns>
        [ChildActionOnly]
        public ActionResult GetCartSummary()
        {
            var shoppingCart = Cart.GetCart(this.HttpContext);

            ViewData["CartEntryCount"] = shoppingCart.GetCartCount();
            return PartialView("CartSummary");
        }
    }
}

DFShop/Controllers/StoreController.cs
using DFShop.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DFShop.Controllers
{
    public class StoreController : Controller
    {
        DontFretEntities db = new DontFretEntities();
        /// <summary>
        /// Controller Function for loading the main store page
        /// </summary>
        /// <returns>view with list of categories</returns>
        public ActionResult Index()
        {
            var categories = db.Categories.ToList();
            return View(categories);
        }

        /// <summary>
        /// Sub-menu to select product categories
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult CategorySelect()
        {
            var categorySelection = db.Categories.ToList();
            return PartialView(categorySelection);
        }

        /// <summary>
        /// Controller Function for browsing products + santizing category selection
        /// </summary>
        /// <param name="category"></param>
        /// <returns>Products View</returns>
        public ActionResult Browse(string category)
        {
            var CategoryModel = db.Categories.Include("Products")
                .Single(c => c.CategoryName == category);

            return View(CategoryModel);
        }

        /// <summary>
        /// Controller Function for looking at individual products
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Product Details view</returns>
        public ActionResult Details(int id)
        {
            var product = db.Products.Find(id);

            return View(product);
        }
    }
}

DFShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Don't Fret Music</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="header"></div>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="#"><h2>@Html.ActionLink("Don't Fret", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</h2></a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <button type="button" class="btn btn-secondary">@Html.ActionLink("Browse", "Index", "Store")</button>
            </li>
            <li class="nav-item">
                <button type="button" class="btn btn-secondary">@Html.ActionLink("About", "About", "Home")</button>
            </li>
            <li class="nav-item">
                <button type="button" class="btn btn-secondary">@Html.ActionLink("Contact", "Contact", "Home")</button>
            </li>
            @if (User.IsInRole("Store Manager") || User.IsInRole("Assistant Manager"))
            {
                <li class="nav-item">
                    <button type="button" class="btn btn-secondary">@Html.ActionLink("Manage Products", "Index", "Products")</button>
                </li>
            }

            <li class="nav-item">
                <button type="button" class="btn btn--secondary">
                    @{Html.RenderAction("GetCartSummary", "Cart");}
                </button>
            </li>
            <li class="nav-item">
                @Html.Partial("_LoginPartial")
            </li>
        </ul>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dont Fret Music</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("stripe", required: false)

</body>
</html>